{% set name = "windpowerlib" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/windpowerlib-{{ version }}.tar.gz
  sha256: f585da2e0abf3cc371c5e75f275dec6bc984835fb6a7921a00f143d7973feeee

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pandas >=0.20.0
    - python >={{ python_min }}
    - numpy
    - requests

test:
  imports:
    - windpowerlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/wind-python/windpowerlib
  summary: Creating time series of wind power plants.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kyri-petrou
